# Generated by Django 4.2.4 on 2024-08-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='film_add',
            new_name='add_film',
        ),
    ]
