# Generated by Django 4.2.4 on 2024-08-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0002_rename_film_add_add_film'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_film',
            new_name='film_add',
        ),
    ]
