# Generated by Django 4.2.4 on 2024-08-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0003_rename_add_film_film_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='film_add',
            new_name='FilmAdd',
        ),
    ]
